apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: development
  namespace: argocd
spec:
  description: Development environment
  destinations:
  - name: 'app-*-dev'
    namespace: ns-*-dev
    server: '*'
  sourceRepos:
  - '*'
  clusterResourceWhitelist:
    - group: ''
      kind: Namespace
