apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: infrastructure
  namespace: argocd
spec:
  description: Infrastructure
  destinations:
  - name: 'app-*-inf'
    namespace: 'ns-*-inf'
    server: '*'
  - name: 'app-*-inf'
    namespace: 'kube-system'
    server: '*'
  sourceRepos:
  - '*'
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
