apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: production
  namespace: argocd
spec:
  description: Production environment
  destinations:
  - name: '*'
    namespace: ns-*-prd
    server: '*'
  sourceRepos:
  - '*'
  clusterResourceWhitelist:
    - group: ''
      kind: Namespace
