apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: acr-externalsecret
spec:
  refreshInterval: 8760h
  secretStoreRef:
    name: azure-kv-store
    kind: ClusterSecretStore

  target:
    name: acr-secret
    creationPolicy: Owner
    template:
      engineVersion: v2     
      type: kubernetes.io/dockerconfigjson
      data:
        .dockerconfigjson: |
          {{- $p := dict "password" .acr_password -}}
          {{- printf "{\"auths\":{\"crrvmaindev.azurecr.io\":{\"username\":\"crrvmaindev\",\"password\":%s}}}" ($p.password | toJson) | nindent 0 }}

  data:
    - secretKey: acr_password
      remoteRef:
        key: container-registry-password
