apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-azurefile-csi-driver-inf
  namespace: argocd
spec:
  project: infrastructure
  source:
    repoURL: https://raw.githubusercontent.com/kubernetes-sigs/azurefile-csi-driver/master/charts
    chart: azurefile-csi-driver
    targetRevision: 1.34.2   
    helm:
      values: |
        controller:
          runOnMaster: true
        node:
          tolerations:
            - key: node-role.kubernetes.io/control-plane
              effect: NoSchedule
            - key: node-role.kubernetes.io/master
              effect: NoSchedule
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - Replace=true