apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-cloudnativepg
  namespace: argocd
spec:
  project: infrastructure
  source:
    repoURL: https://cloudnative-pg.github.io/charts
    targetRevision: 0.26.1
    chart: cloudnative-pg
    helm:
      releaseName: cloudnativepg
      postRenderer:
        kustomize:
          patchesJson6902:
            - target:
                group: apiextensions.k8s.io
                version: v1
                kind: CustomResourceDefinition
                name: poolers.postgresql.cnpg.io
              patch: |-
                - op: remove
                  path: /metadata/annotations/kubectl.kubernetes.io~1last-applied-configuration
  destination:
    server: https://kubernetes.default.svc
    namespace: cnpg-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true