apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-cloudnativepg
  namespace: argocd
spec:
  project: infrastructure
  source:
    repoURL: https://github.com/cloudnative-pg/cloudnative-pg.git
    targetRevision: v1.27.1
    path: deploy
  destination:
    server: https://kubernetes.default.svc
    namespace: cnpg-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true