apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-external-secrets-operator-inf
  namespace: argocd
spec:
  project: infrastructure
  source:
    repoURL: https://charts.external-secrets.io
    chart: ns-external-secrets-inf
    targetRevision: 1.0.0
    helm:
      values: |
        installCRDs: true
  destination:
    server: https://kubernetes.default.svc
    namespace: ns-external-secrets-inf
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true