apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kyverno
  namespace: argocd
spec:
  project: infrastructure
  source:
    repoURL: https://kyverno.github.io/kyverno/
    chart: kyverno
    targetRevision: 3.6.0
    helm:
      values: |
        installCRDs: true
        replicaCount: 2
        nodeSelector:
          kubernetes.io/os: linux
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
        admissionController:
          mutations: true
          validations: true
          backgroundScan: true
  destination:
    server: https://kubernetes.default.svc
    namespace: kyverno
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true