apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-signoz-inf
  namespace: argocd
spec:
  project: infrastructure
  source:
    repoURL: https://charts.signoz.io
    chart: signoz
    targetRevision: 0.104.0
    helm:
      releaseName: signoz
      values: |
        platform: kubernetes
        otelCollector:
          enabled: true
          config:
            receivers:
              k8s_cluster:
                collection_interval: 10s
              kubeletstats:
                collection_interval: 15s
                insecure: true
            processors:
              batch:
                timeout: 10s
            exporters:
              otlp:
                endpoint: signoz-query-service:4317
            service:
              pipelines:
                metrics:
                  receivers: [k8s_cluster, kubeletstats]
                  processors: [batch]
                  exporters: [otlp]
  destination:
    server: https://kubernetes.default.svc
    namespace: ns-signoz-inf
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true      
    - ServerSideApply=true    