apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: smb-storage
  namespace: argocd
spec:
  project: infrastructure
  source:
    repoURL: https://github.com/d3v1anc3/argocd-test.git
    targetRevision: main
    path: apps/infra/smb-storage
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true